apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab01-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /tmp/lab01-pv