apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab01-pvc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  volumeName: lab01-pv