apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  labels:
    app: lab01
spec:
  containers:
  - name: lab01
    image: "rolandop/lab01:15"
    env: 
      - name: VARIABLE_ENTORNO_1
        valueFrom:
          configMapKeyRef:
            name: lab01-config
            key: variable_entorno_1
      - name: VARIABLE_ENTORNO_2
        valueFrom:
          configMapKeyRef:
            name: lab01-config
            key: variable_entorno_2
    volumeMounts:
      - mountPath: /var/Lab/logs
        name: logs
      - mountPath: /var/Lab/props
        name: props
    ports:
    - containerPort: 80
      name: http
  volumes:
    - name: logs
      emptyDir: {} 
    - name: props
      configMap:
        name: lab01-config
        items:
        - key: "lab.properties"
          path: "lab.properties"