# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: lab01
data:
  username: YWRtaW4=
  password: UGEkJHdvcmQuMTIz