apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    app: lab01
spec:
  containers:
  - name: lab01
    image: "rolandop/lab01:15"
    env: 
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: password
    volumeMounts:
      - mountPath: /var/Lab/logs
        name: logs    
    ports:
    - containerPort: 80
      name: http
  volumes:
    - name: logs
      emptyDir: {}    